apiVersion: postgresql.cnpg.io/v1
kind: Cluster

metadata:
  name: postgres
  namespace: gitea

spec:
  instances: 1

  imageName: ghcr.io/cloudnative-pg/postgresql:17

  storage:
    size: 5Gi

  bootstrap:
    initdb:
      database: gitea
      owner: gitea
      secret:
        name: gitea-db-secret