---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-db-secret
  namespace: gitea
spec:
  encryptedData:
    password: AgAKg7HcL2W9wMUHxUnLV5DFPwNL28OZZHHwjdffMXy/NQQp4qyuizWpGL0+qDbeDBuK+wSXLhuYgmNI0m4UiJu/Po2m+1+MY0iulCkBM6OrJZflG6QcqZ7AgP8zFPwrLoiG53p3450vVgeBt65zOOUJf6SYNFgEHfJx7D0YcIl61nK2fGzYB/tuwYPo82jei4CaHzTACIsi3G8LQv134GvMM5IR3HzBHjla5jjhBdkyI/4q9tERU9ZnJ/rt2F40y0EJ1i0jVwRDR7YBjB4ut6GH0bW8YRVXb6IhuQI81y51eQUSgMsFfNhyeQ44H2RYrNmeLKa326ytM7gmSySIJ/IUBSAE23kcODQfKuVSdHk1zuoGma34K6+sXYj/JMnwxGU1tYtVt3bN37cqh/8T/R/DEfeov7j6FL0J00tmXjB8oMFXVOfJf9O4LpHAT8RjEI/rglDBKxTx+LfZKIipjBZ6lrKFFJy3BeD+Mh5B/InovCoOR45hzL3JqgD+qXzsQRZIwx1r/cQIL3CyjhvFoKJ0RE+a2JlRX1W3Bfw4bYcCK1KPkP61A3ewcZLqPaTIsjUuUzRmmAI9tRFj/lakQLz4JGU88ww5SgZ4IGxgNfHeZLEUOFJ5CxRKCJof1MQO+s2PmheWvufhQ8iMAEEHxISOEK/OMGsJMIcLGu13hSvzzbuGnkAAuvM9FiKbGWSAzVgqPh2YiQKa6I1Vwv/XqGFNCe1YMEL9mLfWAxlKryQXfw==
    username: AgCDZK0mKg6BjCnJAz+sx4YpTMDXP8s1/s3/PtCmyauEnTqC1uMEcPHlTbqhENFAuKKsE6mXSf7+5qUORCtEze2C1lDvUrquVwyAxJ6B4TSXdpJuREBdZNF7lzhocmrCdsLyJu4ElkevKVJKtsF1ajepDohbfb0FBAS2j5DUMrhoHlaOybrjdjLhvIVl1EFHErNxPxjl0MrjP1ettW6V7DZqr2cZusYJ3eT3wDUE4OlWeId61JoHPLngargMj0kn/kGlyTMT1MujkU5YLmbfHlyE/80FPkF7P1tAcGyQrvUHNo9bUnQe1oCGusFer9LvRTKXQ9MGwyUHD2xCaHl4HCOb8TYKsr7XNfq11juI2MqGiXgwvVhJSJ8fK/6krN67qv4hI0FUfHu7U26F4wVZGYBQrqzfo70QplHEi8tv8PQfkjlMsNW3PgzQYnTD/ufmHV6P1qVMyl0DLksupXZuR71hg/ZY5z/U3Owho01I5Ot9TOeQYZ/dhRyl6S5+TzPWQ1FSVRiygsz2KsjdRRITZfctQ7An0P7SAE7HhIsbq+lDUv0lwpPj/b7dgSXJ70U3U6jxpYMHLxKfMHdWp6rmN1mzpSZIzn8Usen8SBXgFCVUm6fDEffn2HFTFXqPSGzkUZ0X6RYMJ5sPQtrqU50CYjWc4d+/lZPoFa0njkylNZ/WfnHhZSlyBu5JWp1Sq9U4X3Bc1GydlA==
  template:
    metadata:
      name: gitea-db-secret
      namespace: gitea
    type: kubernetes.io/basic-auth
