apiVersion: apps/v1
kind: Deployment

metadata:
  name: gitea-runner
  namespace: gitea

spec:
  replicas: 1

  selector:
    matchLabels:
      app: gitea-runner

  template:
    metadata:
      labels:
        app: gitea-runner

    spec:

      initContainers:

      - name: dind

        image: docker:27-dind

        restartPolicy: Always

        securityContext:
          privileged: true

        args:
        - --insecure-registry=docker.home.arpa
        - --insecure-registry=docker-registry.docker-registry.svc.cluster.local:5000

        env:

        - name: DOCKER_TLS_CERTDIR
          value: ""

        startupProbe:
          exec:
            command: ["test", "-S", "/var/run/docker.sock"]
          periodSeconds: 1
          failureThreshold: 30

        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi

        volumeMounts:

        - name: docker-run
          mountPath: /var/run

      containers:

      - name: runner

        image: gitea/act_runner:0.2.11

        env:

        - name: DOCKER_HOST
          value: unix:///var/run/docker.sock

        - name: GITEA_INSTANCE_URL
          value: http://gitea.gitea.svc.cluster.local:3000

        - name: GITEA_RUNNER_NAME
          value: k3s-act-runner

        - name: GITEA_RUNNER_REGISTRATION_TOKEN
          valueFrom:
            secretKeyRef:
              name: gitea-runner-secret
              key: token

        - name: CONFIG_FILE
          value: /config/config.yaml

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

        volumeMounts:

        - name: data
          mountPath: /data

        - name: config
          mountPath: /config

        - name: docker-run
          mountPath: /var/run

      volumes:

      - name: data
        persistentVolumeClaim:
          claimName: gitea-runner-data

      - name: config
        configMap:
          name: gitea-runner-config

      - name: docker-run
        emptyDir: {}
