---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-runner-secret
  namespace: gitea
spec:
  encryptedData:
    token: AgAo/E9gWB7eLwTX/fLmKLriMkoWY6atOuUZJ4WNZc5P3gWk4mj0Rdw1bzxbrXrO4j5UYlsUwudoq60m46DbsdEesYN6kjjqiqQYYLDV86c0m9xeiByzRHkRK/REbxIIUTbLSud8G2zbzbB4QtB6FNUdQ1bcv2B6JIEPEEwOJSupUZHOzh3GzWfIcHIPL9LGCox05fOXMfHTeBYysmz5Je1FfPSK7bPcJidtTJrzu2U/vqEXfes2XKNpEmm4C2BerTgjd1v3ZymEmX7pKzpLdKYLnPYF8xfle7m0KPCCMthTCfM76rVClg4DNsLxjjIJcxgdd3i6gCiFkP2x7MRR3j+pU8HOoAqVPQFFdhsWC0plzDbLpAiGQiHCP+F7vE5L2vxRIXQwxoO3ZPigq+vCtA8AdvBM3HK0X6yF/p9eaRrAY2gy6dB1PY4jAxqG+F0+DFHojLigDblld+qD7GiBOQFZXl6J+9NXeg8TkAbQvmWTYpV5b7Hxin4qb3KDA9WYqqnAtAXccjP4lQ6AU9YW2Bq4MJDOqdqjoEjjkfk8rnQ1OdSJ5ihN8t0w93fJyS/wWGykCEmZWdhsv264pNUgEDZ/d2Ck1QE3WXAK+EZDZY4lDu/5Pvl2VJ+d/qGLt2Uere5c2PTVH5GQd3o2Jpol3COHs520w+uQ2jDBn6PfUWIo724mM3F3rsmYYfH54HXwxcVQbyzycLCUusqDqhcAgCK1gxQbeWy24qeDmwZYl23mxl/7gAr3G2vv
  template:
    metadata:
      name: gitea-runner-secret
      namespace: gitea
