apiVersion: apps/v1
kind: Deployment

metadata:
  name: hello-app
  namespace: hello-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: hello-app

  template:
    metadata:
      labels:
        app: hello-app

    spec:
      containers:
      - name: hello-app
        image: docker.home.arpa/hello-app:86a790db3f57239a93c06c1bb21f879be8532475

        ports:
        - containerPort: 80

        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
