apiVersion: v1
kind: Secret

metadata:
  name: gitea-secret
  namespace: gitea

type: Opaque

stringData:

  GITEA__database__PASSWD: Spoon19

  GITEA__security__SECRET_KEY: change-me-secret-key

  GITEA__security__INTERNAL_TOKEN: change-me-internal-token

  GITEA__oauth2__JWT_SECRET: change-me-jwt-secret

  GITEA__server__LFS_JWT_SECRET: change-me-lfs-secret