apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
  namespace: n8n
data:
  N8N_HOST: "n8n.home.arpa"
  N8N_PROTOCOL: "https"
  N8N_PORT: "5678"
  WEBHOOK_URL: "https://n8n.home.arpa/"
  GENERIC_TIMEZONE: "Asia/Baku"
  TZ: "Asia/Baku"
  N8N_DEFAULT_BINARY_DATA_MODE: "filesystem"
  N8N_RUNNERS_ENABLED: "true"
  N8N_METRICS: "false"
  N8N_EMAIL_MODE: "smtp"
  N8N_SMTP_HOST: "smtp.gmail.com"
  N8N_SMTP_PORT: "465"
  N8N_SMTP_USER: "tural.hajibayli19@gmail.com"
  N8N_SMTP_SENDER: "n8n Home <tural.hajibayli19@gmail.com>"
  N8N_SMTP_SSL: "true"
