---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-secret
  namespace: n8n
spec:
  encryptedData:
    DB_POSTGRESDB_PASSWORD: AgCuqrsrzabGlaGYGjAfPDJFINvcKyUiuteCPm9fKBovDr0RCAwtXwgKs3WidMcdrzp+w/Q9DhGF0kD4Fcg+gu+x3QJ5UrjGhlSuLyCHtmSxY/9OZSv9LAJGdqFnevu2CVHLKQcGHPnhM2h084LA3c03UyiJOWb228lnvxhviUFE5rnEHxrh8hMwZ9B/H9oSOEX1EZiK4w5RqQccmmDxN/BrwInc/Mq2dbz4qLoc+I7D1FD7ccHzp6sCG9H/WuM2RSHnQILydmNq9fZBsLoWrXfFTUhRaFGsRqC+HzsaK0xybp1QjAYpxPjpTMxom8eG2mQK/a6CCPm/S+CgWwHBNDyFKn3tZmzSOQ8V/b91wlGyERhRrz3lD6rdBTFPY92mkBtFmbUQg7Cpk0JUNGXDayEQ6d+lh1yi/unOeqmLH1cn/H8lOpynoB+r262v0zsxPJLbCOCFLHQSnvaxGl7VeDLdrrBpX65W8foB+i2f1I0pg7Xuj5YN0voPNpjOeQGl8DHb0haNyEpDXdAaTg6eBxlQnpqlVnn88s1dX/ftht35R24eHn2TzWR1LkqyKGPL9FC6L2YsPZW9v0MHa5sNAwd7mQKG+odXacuJ8PPGdt40j1ALxjUaraY7adjLDef+bAxNGfjZbNMa4oG+n4+Nf7SRC0aWE+bGyyyRsN1k9f/B8DcAr5q0VlUufM8DNuYKSzG/9CBQ6lKIOD+z
    DB_POSTGRESDB_USER: AgADCT0W2uiyNvQJu1IHKlm3xO2HOJgOz3aXd5yys/nr9z3SAT8/979ATOVn3e7v9un7vRQ74y7gdbu1omNRJsL4gjYopzmCjlee99U1HQ/SCO9PdjfU0SudffTIjS5pzm9rb4MEl9vQco6gKcXKGQdakniRpUn0+6gvBaX6XXPGJd48gsdnGHitLgDrBSo3AuL8479cWCF0cYTDiAoUmEqz5i5PjAJHjQv0fnlMthP5I/t6dSh0o8UgQDo/1JLQi6slC75x3Q9XOFzAXW1g9fkcXoPkJaiivILwhgQXokioCnl5B3uGCkknP3zlwLdvm0/ZyiDHAIrJ8b9iGpXvCmhq5NvDdw+tcX8Rthe3pt0Ddo1cYD/YWoiooYo9UI2d59dkB7A3uUCMrqi5+SFDN0yI6airKFK/rTfOauYZom2dt3KvfXoBLKc5Cdlbk2GTWI8J1ctc0ZvmRcaTer0Db2aqCvEgbafXGw9UdRIfi7JQ3SoOrm+r5Il2ysoVCzY5JNzcNAFfwN4rXf8hdjXWw93ZOIFg8ZUqdMDtkcx93bsjrlK2geZCPkeaDLyM3tLqr/GuY9uw5gsQIVyAP5a9esuH7QReRp+cTsDDs9UKMonwD3yxypS6kR+mZNSUxG2u7gIBl1ri8nRDtY0/rzf2VDl0r/gc5aUJWAZZf155NzNrvhIblm685aJktb7gQooB6oM/wcwhhahaew==
  template:
    metadata:
      name: n8n-secret
      namespace: n8n
    type: Opaque
