---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-secret
  namespace: n8n
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgBJbmdDzXsLbF2Md/KfY9WIcQMFHp4YUlDRYcKRTjns5+5GPiis2DciyPBiFG2fx3o8yPpyWYceMrpuevuqwlvm797xk5UgbDx/6kydRU3Qt/FU0ql70PsDAZpn8bZVsmUFpicPqzrxvYgxjF1hB5JDmg2cC+Mq/2W9/yDe8SYKx4e6wBHOUAnQ4plAq5t4K14iBUHcGImDfCUjI9eV03KkXDq8t66qzskkindxide/8lF5F0drvsSVe2+twdmnABdr75a/Q501I8aejYzvmCUkdcK1Sq2CeYkyQ5fVkcmb0zHviqfguzyPoTmFPoYUgSo0D1j265E9y9hinr5you6IywinM7NItf0ebzIH4CNKgpt1oHz+ImtdVne/4PgtJ8heGPhHJ1K9ouwLgDS9VXXpqYTV2QNnL1TQl/5eJ2Y+LUEa0wuYJO1GMd/pTRJ0/Jtn06OG1nebsuR0GH21NxS5d5SMC+m9dKPwg3c3vpdYflJg6WAstUIEQZWeCeXZYwnuTt4Yqk14G3PSnCRSXUvSfo6RokbnWWTUSIVLrFBhqRmkNKdIt5rYzBz1sgADK5PbvX8b0spAXxMAOq3K3lQ2SLqWcWMxlt+Y297ybzLOjw9SV0s74jCipSsFMniKRkmUgkJfqLMGM9g0alx/TjfSIes9caO9tzRE/aHNxc5wP0ooixcLKN2yZ/R407IGkbmH+O/otCDm4+4IO7khTlGkBKvMxqCNvNBeociSOwJ5slwaCT2Ml043nte5Ng==
    N8N_SMTP_PASS: AgBK6IOvz9756qlGIuJWOG35UsjCld6EjMhctxXIy5R18R2WSFUXPRTBFIRJ/W9afJTCrBSIYgrwPwv7UvooWwBUGgHBNuUaXfoE+S6c3sfeKpa6OPwMlSmB7ZRmu21IbFZg0i9rY6XQRTCFaZNUW7Ff8II6zy/khOVhYCWGLN2VhY9YcRpAFP03JoeKY+ZCqEFwpGQ3zMhl0dG8IIo29aVJ3g2L3I+1xi7tvfZD7YJg4hcpFOTD8Qeu0Tyvngm3dBg5HQFaVuBQnVSbtUpyITCPLrQvJ53P7HHARMtI9d44QznXMAOHKnkOC0FRV+JPZ9brgRtTf19CpLORQ0P9IZ3yItBLSpOl0hz6Z6X9xh3CKzHZabFRAk7NRd49d3pfE8EoYfMYrd9maSH+Icz14rF/pKYwHrCOMXxnXnTGrtr2P+fuiMhiEJhoGFBC5jy1TXaGKFf8ECEnvTaHNPiWEgq+/+wVDiz/9FhxGvnTtagaWtFrrI7aVQsynzpvWLjDomqy9/qNKKSuFbmsVSA0/QqchYlGIj8CBsDnqiVynZnuZEuaPl1OIOUp7pGVPgRGuNBmaWgAMpCheiG9t/jhNnjx8Zswafeh5rTIMjZVvYycU4ZfsFUTSZNHKgwVe+cCh/qpONrbDiTIBpjtcKtQA0bVRosMrjrhxa1MvKpBW7Pl/V+TLXRL2L/7QPZRM1gHpX4=
  template:
    metadata:
      name: n8n-secret
      namespace: n8n
