apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-secret
  namespace: n8n
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: Ch/o+ULDCoeW2x5YHwvFOO/CpNuiKqRnmFO5E3s3eGo=
  template:
    metadata:
      name: n8n-secret
      namespace: n8n
    type: Opaque
