---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: act-runner-secret
  namespace: gitea
spec:
  encryptedData:
    token: AgBil7cCkeN95VBOeGCtJhbGtqLhaiA8z+MM16sashb2qk7DGvWQoZsdvUGMJT4vul3YexP4I/96ooV3sX6bKw91DyQmMGWVBWPDYuKRjqLxTYeHP2YEq+c3rHwoECvpq0IP7ipdN16EdjO/jZCnQd76sjUzRrHSqOy8e0/acBCzGgLhY2gEw3nu4+fk13KPxoyg8E6hRV2pxxJ7rOo/1o664EHlPKjZQU6QzArjnVJj9BEJqq6QuiXDSjl/2J7dmhsGENh5J6tPdmR3zAD5SubdM/08/qyFeUMJ7bFDjUNpMZcb4Q/7ndQQvk5k41t08ixv7OfK1f8qhtN5lmwVbLdEekEPL04q82u0NPXhvpYNeyFlbH2nh7SN5Sbu/8R3RlvUuchhveq5AHBl4ffHVriLtU442cIgau+WOvjZNPu4D5XjPW2soJ8ImvyTpFQWZTaa6V8TgoZ+D9CaQPY4+pTtxDHcbeYb480n3SBiJ5YV29kAkL6VCXFJCxpNun0jVeqgDy1A7+eLXEIV9oNWSyjA68zZe22+jBKRFkfgaIZ5mVEtbpdLjrOP6KOyVEzn/xGfkI7r8YzeUWo+2w6NpEgL+Znp9H3iauMnnJApmDBpkq8irY9n2IHNCKTtDSKqzB5J0ywXqVQt/XVAdywi+R0NrGht2gp4krhe8pLPx8wNcBER5J6cLmuIwt/nzvjMamYE6oj1T2VIFgsQDo/W+vgqWfwS6q9NY3FF3jq+dkYkJHZ5vT/b4tSy
  template:
    metadata:
      name: act-runner-secret
      namespace: gitea
