strategy:
  type: Recreate

persistence:
  enabled: true
  size: 5Gi

postgresql:
  enabled: false

postgresql-ha:
  enabled: false

redis:
  enabled: false

redis-cluster:
  enabled: false

valkey:
  enabled: false

valkey-cluster:
  enabled: false

gitea:
  admin:
    username: gitea
    password: Spoon19
    email: admin@home.arpa

  config:

    database:
      DB_TYPE: postgres
      HOST: postgres-rw.gitea.svc.cluster.local:5432
      NAME: gitea
      USER: gitea
      PASSWD: gitea123

    cache:
      ADAPTER: redis
      HOST: valkey.gitea.svc.cluster.local:6379

    session:
      PROVIDER: redis
      PROVIDER_CONFIG: network=tcp,addr=valkey.gitea.svc.cluster.local:6379

service:
  http:
    type: ClusterIP

ingress:
  enabled: false