auth:
  postgresPassword: postgres
  username: gitea
  password: gitea
  database: gitea

architecture: standalone

primary:
  persistence:
    enabled: true
    size: 5Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi

  limits:
    cpu: 500m
    memory: 512Mi